apiVersion: v1
kind: Pod
metadata:
  generateName: busybox-
  annotations:
    k8s.v1.cni.cncf.io/networks: br0
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["tail", "-f", "/dev/null"]
    securityContext:
      capabilities:
        add: ["NET_ADMIN"] 
